export const ErrorCodes = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION: "VALIDATION",
  NOT_FOUND: "NOT_FOUND",
  INSUFFICIENT_STOCK: "INSUFFICIENT_STOCK",
  IDEMPOTENT_REPLAY: "IDEMPOTENT_REPLAY",
  SHIFT_REQUIRED: "SHIFT_REQUIRED",
  SHIFT_ALREADY_OPEN: "SHIFT_ALREADY_OPEN",
  DUPLICATE_VARIANT: "DUPLICATE_VARIANT",
  ENTITLEMENT: "ENTITLEMENT",
  TENANT_MISMATCH: "TENANT_MISMATCH",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
