ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "discountType" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "discountValue" DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "discountReason" TEXT;
ALTER TABLE "PlatformInvoice" ADD COLUMN IF NOT EXISTS "subtotal" DECIMAL(19,4);
ALTER TABLE "PlatformInvoice" ADD COLUMN IF NOT EXISTS "discountType" TEXT NOT NULL DEFAULT 'NONE';
ALTER TABLE "PlatformInvoice" ADD COLUMN IF NOT EXISTS "discountValue" DECIMAL(19,4) NOT NULL DEFAULT 0;
ALTER TABLE "PlatformInvoice" ADD COLUMN IF NOT EXISTS "discountAmount" DECIMAL(19,4) NOT NULL DEFAULT 0;
UPDATE "PlatformInvoice" SET "subtotal" = "amount" WHERE "subtotal" IS NULL;
